:vsc: VS{nbsp}Code

# CONTRIBUTING

## This is the CONTRIBUTING file for the “vscode-yseopml” project

This folder contains the {vsc}{nbsp}extension that runs a YML (Yseop Markup Language) language server.

The extension observes all “yml”{nbsp}documents (documents from all editors associated to the YML{nbsp}language –{nbsp}kao{nbsp}files, yclass{nbsp}files, etc.) and uses the server to provide validation and completion suggestions.

The code for the extension is in the `client`{nbsp}directory. It uses the `vscode-languageclient`{nbsp}node module to launch the language server.

The language server is located in the `server`{nbsp}directory.


## How to run locally

. Run `npm install` to initialize the extension and the server.
. Run `npm run compile` to compile the extension and the server.
. Open this folder in {vsc}. In the “Debug” viewlet, run “Launch Client” from drop-down to launch the extension and attach to the extension.
. Open `test.kao` which is in the `client/test` folder.
. To debug the server, use the “Attach to Server” launch config.
. Set breakpoints in the client or the server.


## How to generate antlr4 files

. If you did not already, install `ANTLR tool` as explained http://www.antlr.org/download.html[here] and https://github.com/antlr/antlr4/blob/master/doc/getting-started.md[here].
. Edit the `YmlParser.g4` or the `YmlLexer.g4` grammar files.
. Run `npm run antlr4ts` to generate tokens, lexer and parser files.


## How to update syntax highlighting

In order to update the syntax highlighting, you must edit `syntaxes/yml.tmLanguage.YAML-tmLanguage` using http://manual.macromates.com/en/language_grammars#language_grammars[the TextMate manual] as reference. Then you need to convert this file into JSON https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#using-yaml-to-write-a-grammar[as indicated here] and replace the content of `syntaxes/yml.tmLanguage.json` which is the file used by the extension for syntax highlighting.

The format used throughout this manual is slightly different from the one we are using{nbsp}(JSON). It is, however, easy to understand how to adapt examples.

[NOTE]
====
We use YAML format to develop the syntax highlighting because YAML:

* allows comments in the code;
* makes regular expression edition way easier because we don't need to escape many characters.

For more information, check https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#using-yaml-to-write-a-grammar[the VS Code extension manual] about using YAML to write a grammar.
====

## Package the extension

Run the following command in your terminal:

```[bash]
npm run package
```

It should end with a line like:

```
Created: /PATH/TO/vscode-yseopml/vscode-yseopml-X.X.X.vsix
```

This `vsix`{nbsp}file in the `client`{nbsp}directory is the packaged extension that can be provided to {vsc} to install the extension.


## Install the extension

### From the command line

```[bash]
code --install-extension EXTENSION_FILE.vsix
```

While developing and testing, lazy Linux users can also use the local `install.sh`{nbsp}script, which runs `npm run package` and retrieves the `vsix`{nbsp}file to install it immediately.


### Via the GUI

. Open the {vsc}{nbsp}command console with `Ctrl + Shift + P`.
. Type “vsix” to search for the command “Install Extension from VSIX”.
. Select the extension file and validate.
. Reload {vsc}.
. Open `client/test/test.kao` to check that the extension is working properly.


## Contributing

You're free to contribute to this project as long as you respect its guidelines.

If you add a significant feature to the extension, insert a short description of it into the `README.md`{nbsp}file. Furthermore, available code snippets should be listed in this README to make sure users can know which snippets are available and how to trigger them. This snippet list can be automatically regenerated using `list-snippets.sh`.

Documentation on the subject of snippets can be found https://code.visualstudio.com/docs/editor/userdefinedsnippets[here].
