<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Yseop Markup Language</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#granules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#documentationString</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.yml</string>
            <key>match</key>
            <string>\b(if|while|for|return|foreach|switch|switchExpr|belongsTo|default|case|interface|class|implements|private|extends|overrides)\b</string>
            <key>comment</key>
            <string>All YML keywords that should be highlighted.</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.yml</string>
            <key>match</key>
            <string>\b(\d+)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.yml</string>
            <key>match</key>
            <string>\b(true|false)\b</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.yml</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.yml</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>documentationString</key>
      <dict>
        <key>name</key>
        <string>string.quoted.triple.yml</string>
        <key>begin</key>
        <string>"""</string>
        <key>end</key>
        <string>"""</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.yml</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>granules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.interpolated.yml</string>
            <key>begin</key>
            <string>\\\(</string>
            <key>end</key>
            <string>\\\)</string>
            <key>comment</key>
            <string>Text Granule blocks.</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(//).*</string>
            <key>name</key>
            <string>comment.line.double-slash.yml</string>
            <key>comment</key>
            <string>Single line comment.</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.yml</string>
            <key>comment</key>
            <string>Multilines comments.</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(--?&gt;|/|\+|-|\*|&amp;&amp;?|\|\|?|==?)</string>
            <key>name</key>
            <string>keyword.operator.yml</string>
            <key>comment</key>
            <string>Some of the operators that can be find in YML.</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\w+\(\)</string>
            <key>name</key>
            <string>entity.name.function.yml</string>
            <key>comment</key>
            <string>Any succession of letters followed by empty parenthesis.</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.yseop</string>
  </dict>
</plist>