<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Yseop Markup Language</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#option</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessing</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#granules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#documentationString</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>tag</key>
      <dict>
        <key>begin</key>
        <string>\b</string>
        <key>name</key>
        <string>keyword.control.granule.yml</string>
        <key>match</key>
        <string>\\\w+</string>
        <key>comment</key>
        <string>All YML keywords that should be highlighted.</string>
        <key>end</key>
        <string>\b</string>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.yml</string>
            <key>match</key>
            <string>\b(args|belongsTo|break|case|class|classProperties|complete|default|else|extends|field|for|foreach|function|Function|if|ifExpr|implementation|interface|local|method|override|private|return|static|switch|switchExpr|switchExprExclusive|then|while)\b</string>
            <key>comment</key>
            <string>All YML keywords that should be highlighted.</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?x) \\ (beginAnnotation|beginBookmark|beginChooseSynonym|beginContentTest|forall|foreach|beginFormat|beginIndent|ifBaseLanguage_(de|en|es|fr|ja|nl)|ifLanguage_(de|en(_US|_GB)?|es|fr(_BE|_CA|_FR)?|ja|nl)|beginIndivisible|beginKeepTextAspect|link|beginList|beginNote|beginQuote|beginStyle|beginTimeCounter|beginTitleLevel|if|beginSynonym|while|switch)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.yml</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?x) \\ (endAnnotation|endBookmark|endChooseSynonym|endContentTest|endForall|endForeach|endFormat|endIndent|endIfBaseLanguage_(de|en|es|fr|ja|nl)|endIfLanguage_(de|en(_US|_GB)?|es|fr(_BE|_CA|_FR)?|ja|nl)|endIndivisible|endKeepTextAspect|endLink|endList|endNote|endQuote|endStyle|endTimeCounter|endTitleLevel|endIf|endSynonym|endWhile|endSwitch)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.yml</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(?x) \\ (nextItem|default|case|else|choice)</string>
                <key>name</key>
                <string>keyword.control.yml</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#textgranule-functions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>option</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)(--&gt;|\+\+\+|---|==&gt;)\s+(\w+)\s+</string>
            <key>end</key>
            <string>\n+</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.yseop</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#inlineInstance</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#documentationString</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#granules</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operators</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>\{</string>
                <key>end</key>
                <string>\}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#constants</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#comments</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#strings</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#keywords</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#granules</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#operators</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inlineInstance</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x) (-&gt;) \s* \b(\w+)\b (\s+\b(\w+(:\w+)*(::\w+)?)\b)?</string>
            <key>end</key>
            <string>(?=;)\n*</string>
            <key>name</key>
            <string>entity.other.yseop</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.yseop</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.yseop</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.yseop</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#option</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#granules</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.other.yml</string>
            <key>match</key>
            <string>'d:\d{4}-\d{2}-\d{2}'</string>
            <key>comment</key>
            <string>Dates</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.yml</string>
            <key>match</key>
            <string>\b\d+(\.\d+)?\b</string>
            <key>comment</key>
            <string>A simple integer or a decimal number</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.yml</string>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
            <key>comment</key>
            <string>Pure constants.</string>
          </dict>
        </array>
      </dict>
      <key>preprocessing</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>@if</string>
            <key>end</key>
            <string>@endif</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.yseop</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>meta.preprocessor.yseop</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>@else</string>
                <key>name</key>
                <string>meta.preprocessor.yseop</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operators</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>@pragma</string>
            <key>include</key>
            <string>#functions</string>
            <key>name</key>
            <string>meta.preprocessor.yseop</string>
          </dict>
        </array>
        <key>comment</key>
        <string>Preprocessing stuff</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.yml</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.yml</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
        <key>comment</key>
        <string>All simple strings</string>
      </dict>
      <key>documentationString</key>
      <dict>
        <key>name</key>
        <string>string.quoted.triple.yml</string>
        <key>begin</key>
        <string>"""</string>
        <key>end</key>
        <string>"""</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.yml</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>textgranule-functions</key>
      <dict>
        <key>begin</key>
        <string>\\\w+(::?\w+)*\s*\(</string>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>entity.name.function.granule.yml</string>
        <key>comment</key>
        <string>A tag with arguments.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(\w+)\b</string>
            <key>name</key>
            <string>variable.parameter.yml</string>
            <key>comment</key>
            <string>A parameter is just a string or a number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
        </array>
      </dict>
      <key>granules</key>
      <dict>
        <key>name</key>
        <string>source.granule.yml</string>
        <key>begin</key>
        <string>\\\(</string>
        <key>end</key>
        <string>\\\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#textgranule-functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
        </array>
        <key>comment</key>
        <string>Text Granule blocks.</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(//).*</string>
            <key>name</key>
            <string>comment.line.double-slash.yml</string>
            <key>comment</key>
            <string>Single line comment.</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.yml</string>
            <key>comment</key>
            <string>Multilines comments.</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>match</key>
        <string>(\+\+\+|&gt;|&gt;=|&lt;|&lt;=|==|!=|==&gt;|--?&gt;|/|\+|-|\*|&amp;&amp;?|\|\|?|==?)</string>
        <key>name</key>
        <string>keyword.operator.yml</string>
        <key>comment</key>
        <string>Some of the operators that can be find in YML.</string>
      </dict>
      <key>functions</key>
      <dict>
        <key>begin</key>
        <string>\b\w+(::?\w+)*\s*\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(\w+|\d+)\b</string>
            <key>name</key>
            <string>variable.parameter.yml</string>
            <key>comment</key>
            <string>A parameter is just a string or a number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
        <key>name</key>
        <string>entity.name.function.yml</string>
        <key>comment</key>
        <string>A function call in YML.</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.yseop</string>
  </dict>
</plist>
